import { Metadata } from 'next';
import Link from 'next/link';
export const metadata: Metadata = {
  title: 'Page not found',
  description: 'Generated by create next app',
};

export default function NotFound() {
  return (
    <div className="flex h-screen flex-col items-center justify-center bg-background text-foreground px-4">
      {/* Illustration */}
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 200 200"
        className="h-40 w-40 text-muted-foreground"
        fill="none"
      >
        <circle
          cx="100"
          cy="100"
          r="90"
          stroke="currentColor"
          strokeWidth="8"
        />
        <path
          d="M65 85 L85 105 M85 85 L65 105 M115 85 L135 105 M135 85 L115 105"
          stroke="currentColor"
          strokeWidth="8"
          strokeLinecap="round"
        />
        <path
          d="M70 135 Q100 155 130 135"
          stroke="currentColor"
          strokeWidth="6"
          strokeLinecap="round"
        />
      </svg>

      {/* Heading */}
      <h1 className="mt-6 text-5xl font-extrabold tracking-tight">404</h1>
      <p className="mt-2 text-xl font-semibold">Page not found</p>
      <p className="mt-2 max-w-md text-center text-muted-foreground">
        Sorry, we couldn’t find the page you’re looking for. It may have been
        moved or deleted.
      </p>

      {/* Button */}
      <Link
        href="/"
        className="mt-6 rounded-xl bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-lg transition-colors hover:bg-primary/90"
      >
        Go back home
      </Link>
    </div>
  );
}
